### ISSUE TITLE
main.go:184:15: undefined: Asset

### ISSUE THREAD

**Issue by nenright** [JanDeDobbeleer/homebrew-oh-my-posh#1]
Attempting to install and am getting this:

```
==> go build oh-my-posh
Last 15 lines from /Homebrew/oh-my-posh/01.go:
2020-12-23 16:15:50 -0500

go
build
-o
oh-my-posh

# github.com/jandedobbeleer/oh-my-posh3
./main.go:184:15: undefined: Asset
```

don't know go but attempted to brew install go-bindata but that didn't help.

**Comment by JanDeDobbeleer** [comment]
You're right, I forgot to address this change here. I'll fix it!

**Comment by JanDeDobbeleer** [comment]
@nenright I made a revision and adjusted the template, can you try again? I need to upgrade Xcode first 🤦🏻

**Comment by JanDeDobbeleer** [comment]
@nenright I reverted to 3.58.0 for the time being, will fix with a fresh pair of eyes in the morning.

**Comment by nenright** [comment]
I was able to do the manual install without Homebrew.  Thanks for taking a look though!  Awesome tool.

**Comment by JanDeDobbeleer** [comment]
@nenright can you try again? Somehow I can only install locally, must've ruined my homebrew setup somehow.

**Comment by JanDeDobbeleer** [comment]
<img width="781" alt="image" src="https://user-images.githubusercontent.com/2492783/103088776-2dec6e80-45ec-11eb-8c31-0faef0d147dd.png">

**Comment by nenright** [comment]
Verified the fix with the install via HomeBrew.  Thanks again!
