### ISSUE TITLE
Install `12.17.2` Failure - `Bad address`

### ISSUE THREAD

**Issue by mattcargile** [JanDeDobbeleer/homebrew-oh-my-posh#12]
I receive the output when attempting to install `oh-my-posh` on  `Ubuntu` `22.04.1` on `wsl` `v2.  

I receive `Bad Address` even when I run `go`. Maybe I have done something wrong here.

```log
matt@mypcname:~$ brew install jandedobbeleer/oh-my-posh/oh-my-posh
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).

==> Downloading https://github.com/JanDeDobbeleer/oh-my-posh/archive/v12.17.2.tar.gz
Already downloaded: /home/matt/.cache/Homebrew/downloads/58ce9ef2cf7eefe99d00060359da7fb5ff57477634ca9f5f5926dd6d02fe1ffd--oh-my-posh-12.17.2.tar.gz
==> Installing oh-my-posh from jandedobbeleer/oh-my-posh
==> go build -o=oh-my-posh -ldflags="-s -w -X 'main.Version=12.17.2'"
Last 15 lines from /home/matt/.cache/Homebrew/Logs/oh-my-posh/01.go:
2022-11-21 20:01:03 +0000

go build -o=oh-my-posh -ldflags="-s -w -X 'main.Version=12.17.2'"

sh: 1: go: Bad address
```

**Comment by JanDeDobbeleer** [comment]
@mattcargile it should install go for you, haven't seen this before.

**Comment by mattcargile** [comment]
Yeah it does. I'm doing `wsl --install -d Ubuntu` and it gives me this weird behavior of installing 20.04 and 22.04. Then I `--unregister` 20.04 and then go through the installs on 22.04 and end up in this weird state. I'm trying a new install now with `wsl`.

**Comment by mattcargile** [comment]
Ohh, I bet it is because I am on version 1.

  NAME            STATE           VERSION
* Ubuntu-22.04    Running         1

**Comment by mattcargile** [comment]
Yeah it was because my installation was defaulting to version 1 for some reason. Once I upgraded to version 2, it worked.
