### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by DarkKira98** [JanDeDobbeleer/homebrew-oh-my-posh#15]
Installing oh-my-posh via brew failed with the following messages:
```
go build -o=oh-my-posh -ldflags="-s -w -X 'main.Version=14.14.3'"

sh: 1: go: Bad address
```

**Comment by JanDeDobbeleer** [comment]
@DarkKira98 that's go which didn't install correctly on your machine. Something to retry, or report to homebrew. Not something I can solve. Try reinstalling go manually or report to the homebrew maintainers.
