### ISSUE TITLE
Bad address when I try to install oh-my-posh

### ISSUE THREAD

**Issue by jesuscampos** [JanDeDobbeleer/homebrew-oh-my-posh#17]
I've getting this error when I install oh-my-posh in my Ubuntu 22.04.2 LTS (WSL 1).

Command:

    brew update && brew upgrade oh-my-posh

Output:

    Running `brew update --auto-update`...
    ==> Fetching dependencies for jandedobbeleer/oh-my-posh/oh-my-posh: go@1.20
    ==> Fetching go
    ==> Downloading https://ghcr.io/v2/homebrew/core/go/manifests/1.20.2-1
    Already downloaded: /home/jcampos/.cache/Homebrew/downloads/ee3787b2e5ba7dfc6dc0f54e182818d4cc22135292d3a6e85add5cf82a0fb8ac--go-1.20.2-1.bottle_manifest.json
    ==> Downloading https://ghcr.io/v2/homebrew/core/go/blobs/sha256:868a2d5c202c7436c193c71c3143bfa464658eacc045cf8c59dedd7
    Already downloaded: /home/jcampos/.cache/Homebrew/downloads/b777b4d463d9e4406d1f55f2ca0b3467c101cb5f9740b8c918d3032f1bea26c9--go--1.20.2.x86_64_linux.bottle.1.tar.gz
    ==> Fetching jandedobbeleer/oh-my-posh/oh-my-posh
    ==> Downloading https://github.com/JanDeDobbeleer/oh-my-posh/archive/v14.24.0.tar.gz
    Already downloaded: /home/jcampos/.cache/Homebrew/downloads/b5c0cdb442f5ecde6fa668012d4a1b3e9ddc7ee48804a63990b7c4b98c456157--oh-my-posh-14.24.0.tar.gz
    ==> Installing oh-my-posh from jandedobbeleer/oh-my-posh
    ==> Installing dependencies for jandedobbeleer/oh-my-posh/oh-my-posh: go@1.20
    ==> Installing jandedobbeleer/oh-my-posh/oh-my-posh dependency: go@1.20
    ==> Pouring go--1.20.2.x86_64_linux.bottle.1.tar.gz
    🍺  /home/linuxbrew/.linuxbrew/Cellar/go/1.20.2: 11,975 files, 240.4MB
    ==> Installing jandedobbeleer/oh-my-posh/oh-my-posh
    ==> go build -o=oh-my-posh -ldflags="-s -w -X 'main.Version=14.24.0'"
    Last 15 lines from /home/jcampos/.cache/Homebrew/Logs/oh-my-posh/01.go:
    2023-04-02 16:06:59 +0000
    
    go build -o=oh-my-posh -ldflags="-s -w -X 'main.Version=14.24.0'"
    
    sh: 1: go: Bad address
    
    If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
      https://github.com/jandedobbeleer/homebrew-oh-my-posh/issues

**Comment by JanDeDobbeleer** [comment]
@jesuscampos seems like go wasn't installed correctly, which is a homebrew issue. [Here](https://stackoverflow.com/questions/74614075/bash-home-linuxbrew-linuxbrew-bin-go-bad-address)'s some information on how to solve that.
