### ISSUE TITLE
 <linux/errno.h> no such file or director

### ISSUE THREAD

**Issue by LukaSimon** [JanDeDobbeleer/homebrew-oh-my-posh#19]
Hey there. 
I tried to install oh-my-posh with the brew command and the output was that there was a file or directory missing.

Is this a common problem, and how to fix it?
![Screenshot 2023-08-26 174242](https://github.com/JanDeDobbeleer/homebrew-oh-my-posh/assets/67833829/c4974a6b-d04e-48be-a01e-459973d11ccc)

**Comment by JanDeDobbeleer** [comment]
@LukaSimon you probably don't have build-essentials or other relevant homebrew dependencies on Linux not installed on your machine.
