### ISSUE TITLE
Errors in oh-my-posh file

### ISSUE THREAD

**Issue by LukaSimon** [JanDeDobbeleer/homebrew-oh-my-posh#21]
When I want to run commands like: 

```bash
eval "$(oh-my-posh init bash --config ~/.poshthemes/kali.omp.json)"
```

I get this error message:

![Screenshot 2023-08-26 202603](https://github.com/JanDeDobbeleer/homebrew-oh-my-posh/assets/67833829/06418792-44cc-4948-81ed-febe7a9dad92)

What is causing that?

**Comment by JanDeDobbeleer** [comment]
@LukaSimon you seems to have installed a web page and not the oh-my-posh executable. I think the download failed and installed the HTML.

**Comment by vbreia** [comment]
![image](https://github.com/JanDeDobbeleer/homebrew-oh-my-posh/assets/85040712/ca1ffad8-fa8e-4651-8c04-45fad21c689b)
crying

**Comment by JanDeDobbeleer** [comment]
@vbreia you forgot to install the additional requirements for homebrew on linux. Please read homebrew's installation guide to the [end](https://docs.brew.sh/Homebrew-on-Linux#install).
