### ISSUE TITLE
Warning on changed file over-write during upgrade

### ISSUE THREAD

**Issue by pacanukeha** [JanDeDobbeleer/homebrew-oh-my-posh#23]
It would be nice to get a warning if a file has changed since it was installed and is about to be over-written or deleted.
Not sure how to manage this since brews delete the whole old install dir and create a new one.

**Comment by JanDeDobbeleer** [comment]
@pacanukeha what override would be an issue? If it's about themes, you should never edit those directly from the installation directory, but copy them elsewhere, outside of homebrew's internals.

**Comment by pacanukeha** [comment]
fair point, and you *do* provide
HOMEBREW_NO_INSTALL_CLEANUP
as a fall back. I'm just thinking about some packages like grub or whatever that when you upgrade it gives you the option to keep/merge/replace.  nice-to-have but low priority.  close at will and thanks.
