### ISSUE TITLE
Oh My Posh Installation Error

### ISSUE THREAD

**Issue by awscyber** [JanDeDobbeleer/homebrew-oh-my-posh#27]
https://github.com/JanDeDobbeleer/oh-my-posh/archive/v21.11.0.tar.gz

Last 15 lines from /Users/sathiaba/Library/Logs/Homebrew/oh-my-posh/01.build.Date=2024-06-17T06:47:31Z'":
font/cli.go:9:2: github.com/charmbracelet/bubbles@v0.18.0: Get "https://proxy.golang.org/github.com/charmbracelet/bubbles/@v/v0.18.0.zip": dial tcp: lookup proxy.golang.org: no such host
segments/terraform.go:11:2: github.com/hashicorp/hcl/v2@v2.20.1: Get "https://proxy.golang.org/github.com/hashicorp/hcl/v2/@v/v2.20.1.zip": dial tcp: lookup proxy.golang.org: no such host
segments/terraform.go:12:2: github.com/hashicorp/hcl/v2@v2.20.1: Get "https://proxy.golang.org/github.com/hashicorp/hcl/v2/@v/v2.20.1.zip": dial tcp: lookup proxy.golang.org: no such host
segments/project.go:15:2: github.com/pelletier/go-toml/v2@v2.2.2: Get "https://proxy.golang.org/github.com/pelletier/go-toml/v2/@v/v2.2.2.zip": dial tcp: lookup proxy.golang.org: i/o timeout
segments/argocd.go:11:2: github.com/spf13/pflag@v1.0.5: Get "https://proxy.golang.org/github.com/spf13/pflag/@v/v1.0.5.zip": dial tcp: lookup proxy.golang.org: i/o timeout
segments/project.go:13:2: golang.org/x/exp@v0.0.0-20240613232115-7f521ea00fb8: Get "https://proxy.golang.org/golang.org/x/exp/@v/v0.0.0-20240613232115-7f521ea00fb8.zip": dial tcp: lookup proxy.golang.org: i/o timeout
segments/golang.go:7:2: golang.org/x/mod@v0.18.0: Get "https://proxy.golang.org/golang.org/x/mod/@v/v0.18.0.zip": dial tcp: lookup proxy.golang.org: i/o timeout
segments/executiontime.go:10:2: golang.org/x/text@v0.16.0: Get "https://proxy.golang.org/golang.org/x/text/@v/v0.16.0.zip": dial tcp: lookup proxy.golang.org: i/o timeout
segments/executiontime.go:11:2: golang.org/x/text@v0.16.0: Get "https://proxy.golang.org/golang.org/x/text/@v/v0.16.0.zip": dial tcp: lookup proxy.golang.org: i/o timeout
segments/gcp.go:10:2: gopkg.in/ini.v1@v1.67.0: Get "https://proxy.golang.org/gopkg.in/ini.v1/@v/v1.67.0.zip": dial tcp: lookup proxy.golang.org: no such host
segments/argocd.go:12:2: gopkg.in/yaml.v3@v3.0.1: Get "https://proxy.golang.org/gopkg.in/yaml.v3/@v/v3.0.1.zip": dial tcp: lookup proxy.golang.org: no such host
engine/image.go:45:2: golang.org/x/image@v0.17.0: Get "https://proxy.golang.org/golang.org/x/image/@v/v0.17.0.zip": dial tcp: lookup proxy.golang.org: i/o timeout
engine/image.go:46:2: golang.org/x/image@v0.17.0: Get "https://proxy.golang.org/golang.org/x/image/@v/v0.17.0.zip": dial tcp: lookup proxy.golang.org: i/o timeout
engine/segment.go:16:2: golang.org/x/text@v0.16.0: Get "https://proxy.golang.org/golang.org/x/text/@v/v0.16.0.zip": dial tcp: lookup proxy.golang.org: i/o timeout
cli/args.go:3:8: github.com/spf13/cobra@v1.8.1: Get "https://proxy.golang.org/github.com/spf13/cobra/@v/v1.8.1.zip": dial tcp: lookup proxy.golang.org: no such host

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/jandedobbeleer/homebrew-oh-my-posh/issues

**Comment by JanDeDobbeleer** [comment]
@awscyber as stated in the log, golang can't download the dependencies which is highly likely a network (proxy) issue. This is client side, not an issue with oh-my-posh.
