### ISSUE TITLE
issue install

### ISSUE THREAD

**Issue by kittenvr** [JanDeDobbeleer/homebrew-oh-my-posh#28]
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Fetching jandedobbeleer/oh-my-posh/oh-my-posh
==> Downloading https://github.com/JanDeDobbeleer/oh-my-posh/archive/v21.16.2.tar.gz
Already downloaded: /home/pizzav/.cache/Homebrew/downloads/733d4916e75f4febe7e66ae4793888146098afae98345258bcc39816b1737c75--oh-my-posh-21.16.2.tar.gz
==> Installing oh-my-posh from jandedobbeleer/oh-my-posh
==> go build -o=oh-my-posh -ldflags="-s -w -X 'github.com/jandedobbeleer/oh-my-posh/src/build.Version=21.16.2' -X 'github.com/jandedobbeleer/oh-my-posh/src/build.Date=2024-06-24T19:10:48Z'"
Last 15 lines from /home/pizzav/.cache/Homebrew/Logs/oh-my-posh/01.build.Date=2024-06-24T19:10:48Z'":
2024-06-24 21:32:33 +0000

go build -o=oh-my-posh -ldflags="-s -w -X 'github.com/jandedobbeleer/oh-my-posh/src/build.Version=21.16.2' -X 'github.com/jandedobbeleer/oh-my-posh/src/build.Date=2024-06-24T19:10:48Z'"

# github.com/jandedobbeleer/oh-my-posh/src
/home/linuxbrew/.linuxbrew/Cellar/go/1.22.4/libexec/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
collect2: fatal error: cannot find ‘ld’
compilation terminated.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/jandedobbeleer/homebrew-oh-my-posh/issues

These open issues may also help:
Oh My Posh Installation Error https://github.com/JanDeDobbeleer/homebrew-oh-my-posh/issues/27

**Comment by JanDeDobbeleer** [comment]
> collect2: fatal error: cannot find ‘ld’
compilation terminated.

Pretty sure not all dependencies for homebrew have been installed as indicated in the installation guide. There's a warning block on our [docs](https://ohmyposh.dev/docs/installation/linux#installation) that also mentions this:

> [!WARNING]
> When installing Homebrew for Linux, be sure to follow [Next steps](https://docs.brew.sh/Homebrew-on-Linux#install) instructions to add Homebrew to your PATH and to your bash shell profile script, and [Requirements](https://docs.brew.sh/Homebrew-on-Linux#requirements) to build Oh My Posh.

**Comment by kittenvr** [comment]
> > collect2: fatal error: cannot find ‘ld’
> compilation terminated.
> 
> Pretty sure not all dependencies for homebrew have been installed as indicated in the installation guide. There's a warning block on our [docs](https://ohmyposh.dev/docs/installation/linux#installation) that also mentions this:
> 
> > [!WARNING]
> > When installing Homebrew for Linux, be sure to follow [Next steps](https://docs.brew.sh/Homebrew-on-Linux#install) instructions to add Homebrew to your PATH and to your bash shell profile script, and [Requirements](https://docs.brew.sh/Homebrew-on-Linux#requirements) to build Oh My Posh.
> 

They are

**Comment by JanDeDobbeleer** [comment]
@kittenvr this is still a gcc dependency issue which is distro specific. You'll have to make sure this is also installed and on your PATH. See [this](https://stackoverflow.com/questions/35970824/gcc-collect2-fatal-error-cannot-find-ld) issue for example.
