### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by floh96** [JanDeDobbeleer/homebrew-oh-my-posh#3]
see https://github.com/JanDeDobbeleer/homebrew-oh-my-posh/blob/main/oh-my-posh.rb#L22

**Comment by sgeraldes** [comment]
==> Installing oh-my-posh from jandedobbeleer/oh-my-posh
==> Downloading https://github.com/JanDeDobbeleer/oh-my-posh/archive/v3.162.3.tar.gz
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/downloads/7df46bf21cefd6c92c9f363c96b8e7e1b0c9f8293470879cabd3fb7a82d122bc--oh-my-posh-3.162.3.tar.gz
==> go build -o=oh-my-posh -ldflags="-X 'main.Version=3.162.3'"
Last 15 lines from /Users/xxxx/Library/Logs/Homebrew/oh-my-posh/01.go:
2021-06-08 18:58:42 -0300

go build -o=oh-my-posh -ldflags="-X 'main.Version=3.162.3'"

go: github.com/Masterminds/goutils@v1.1.1: Get "https://proxy.golang.org/github.com/%21masterminds/goutils/@v/v1.1.1.mod": dial tcp: i/o timeout

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/jandedobbeleer/homebrew-oh-my-posh/issues

**Comment by JanDeDobbeleer** [comment]
@sgeraldes that's probably related to the global outages as it can't download the dependency. I'll check.
