### ISSUE TITLE
File or Directory not found

### ISSUE THREAD

**Issue by FishyEatCowy** [JanDeDobbeleer/homebrew-oh-my-posh#30]
go build -o=oh-my-posh -ldflags="-s -w -X 'github.com/jandedobbeleer/oh-my-posh/src/build.Version=23.9.1' -X 'github.com/jandedobbeleer/oh-my-posh/src/build.Date=2024-08-29T16:24:36Z'"

# runtime/cgo
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
    3 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.

**Comment by JanDeDobbeleer** [comment]
@FishyEatCowy you need to have a look at the other homebrew dependencies, this is a homebrew issue, not oh-my-posh.
