### ISSUE TITLE
Path of `themes` directory should be consistent with that in documentation

### ISSUE THREAD

**Issue by lewis-yeung** [JanDeDobbeleer/homebrew-oh-my-posh#8]
In Formula template:

https://github.com/JanDeDobbeleer/homebrew-oh-my-posh/blob/acf2821c53be7c5fd322fe420edadf87857a1c59/build/oh-my-posh.txt#L24

The path of `themes` directory should be consistent with that in the documentation:

> If you want to use a standard theme, you can find them in `$(brew --prefix)/oh-my-posh/themes`, referencing them as such will always keep them compatible when updating Oh My Posh.

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung the docs should be updated. I thought I fixed that already, but guess not.

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer So should it be changed to `$(brew --prefix oh-my-posh)/themes` in the documentation?

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung someone did it change it to what it is now because it didn't work otherwise. So we need to double check.

**Comment by lewis-yeung** [comment]
In the [documentation](https://docs.brew.sh/Manpage#--prefix---unbrewed---installed-formula-) of Homebrew:

> ### `--prefix` [*`--unbrewed`*] [*`--installed`*] [*`formula`* ...]
> 
> Display Homebrew's install path. *Default:*
> 
>   - macOS Intel: `/usr/local`
>   - macOS ARM: `/opt/homebrew`
>   - Linux: `/home/linuxbrew/.linuxbrew`
> 
> If *`formula`* is provided, display the location where *`formula`* is or would be installed.

The original `$(brew --prefix oh-my-posh)/themes` is correct in principle since `mv "themes", prefix` works with a non-platform-specific prefix path. This [commit](https://github.com/JanDeDobbeleer/oh-my-posh/commit/01d5a483efc066da804ce2a1f10f0bdfaf158f93#diff-b2afedb12993eaf8b68db027d185c268be52926e57871fcfa792564a9d35d3b9L13-R13) might have an excessive modification on it.
